Authorization (login + register), GUI
Win4ap/2024-HSE-Project pull request #2
Opened 2024-02-25 20:54 UTC by Win4ap

2024-02-25 20:55 UTC, Win4ap commented
Сервака пока нет, скоро будет, но там в методах уже есть взаимодействие с сервером, пока просто хочется уже что-то рабочее в мастер закинуть

2024-02-26 15:47 UTC, Win4ap commented
Теперь с рабочим сервером, осталось только сделать реакцию GUI на разные ответы сервера

2024-02-26 17:05 UTC, Win4ap commented
Готово, всплывающие окошки информируют пользователя об ошибках при авторизации/регистрации

2024-03-03 21:06 UTC, Alm0x requested changes
В целом неплохо, посмотрите комменты, исправьте и тыкните

2024-03-03 21:06 UTC, Alm0x commented on server/server.py
> +        PORT = 1233
Лучше создать отдельный файлик где будут прописаны все константы

2024-03-03 21:06 UTC, Alm0x commented on server/server.py
> +        print('Start working...')
logging.info вместо print и логи лучше более понятными сделать, чтоб проще дебажить потом было

2024-03-03 21:06 UTC, Alm0x commented on server/server.py
> +            client, address = server.accept() #принятие запроса с разделением на клиента и его адрес, ждем сигнала.
client тоже надо не забыть закрыть когда с ним отработаем, можно использовать with например

2024-03-03 21:06 UTC, Alm0x commented on server/server.py
> +                client.send(('Shutdown...').encode('utf'))
utf ---> utf8?

2024-03-03 21:06 UTC, Alm0x commented on server/server.py
> +        server.close()
лучше close вызывать в finally блоке, чтоб сервак точно закрылся

2024-03-03 21:06 UTC, Alm0x commented on server/server.py
> +        case 'shutdown':
предполагается, что в теории мы можем с клиента послать шатдаун и уронить сервак?
кажется не должно так работать

2024-03-03 21:06 UTC, Alm0x commented on server/server.py
> +            password_input = request[3]
дублирование

2024-03-03 21:06 UTC, Alm0x commented on src/windows/auth.py
> +IP = '127.0.0.1'
то же самое что и по серваку, константы лучше вынести в отдельный файлик

2024-03-03 21:06 UTC, Alm0x commented on src/windows/register.py
> +        self.password_hide_button.text = 'Скрыть пароль' if self.password_hide_button.state == 'down' else 'Показать пароль'
почти полная копипаста AuthWindow, я бы предложил создать надкласс и от него отнаследовать эти 2 класса, чтоб не было дублирования кода

2024-03-03 21:06 UTC, Alm0x commented on src/windows/auth.py
> +    def send_login_request(self):
я бы предложил создать отдельный класс, ответственный за общение с сервером, чтоб:
1)не мешать логику обработки запросов пользователя с логикой взаимодействия с сервером
2)в последующем будет много запросов отсылаться примерно одинакового типа на сервер и обратно и чтоб не было копипасты удобнее будет, если один отдельный объект за это отвечать будет

2024-03-03 21:06 UTC, Alm0x commented on src/windows/auth.py
> +        request = 'login ' + state + ' ' + self.login_input.text + ' ' + self.password_input.text
request = f'login {state} {self.login_input.text} {self.password_input.text}'

2024-03-03 21:06 UTC, Alm0x commented on src/windows/auth.py
> +        client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
чтоб клиент точно закрылся лучше заюзать контекстный менеджер (with например)

2024-03-03 21:06 UTC, Alm0x commented on src/windows/auth.py
> +            Popup(title='Placeholder', content=Label(text='УРА РАБОТАЕТ ЧЕГО??'), size_hint=(0.7, 0.2)).open()
1)обернуть в try блок, вдруг не получится подключиться
2)побольше логгируйте (logging.info/debug)

2024-03-03 21:06 UTC, Alm0x commented on src/windows/auth.py
> +        else:
У вас уже в теории Error может с сервака прилететь, так что лучше elif answer == 'correct' сделать и в else обработать уже непонятную дичь

2024-03-03 21:06 UTC, Alm0x commented on src/windows/register.py
> +            Popup(title='Ошибка', content=Label(text='Разные пароли'), size_hint=(0.7, 0.2)).open()
те же комменты что и для send_login_request

2024-03-14 16:21 UTC, closed without merging